<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>lhs</string>
	</array>
	<key>keyEquivalent</key>
	<string>^~H</string>
	<key>name</key>
	<string>Literate Haskell Bird Style</string>
	<key>patterns</key>
	<array>
		<dict>
            <key>begin</key>
            <string>^&gt;</string>
            <key>end</key>
            <string>$</string>
            <key>patterns</key>
            <array>
                  <dict>
                        <key>include</key>
                        <string>source.haskell</string>
                  </dict>
            </array>
      </dict>
	</array>
	<key>scopeName</key>
	<string>source.haskell.bird</string>
	<key>uuid</key>
	<string>d32ef3c4-1b5e-4782-a1ff-34135f3a5c19</string>
</dict>
</plist>
