<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>cabal</string>
	</array>
	<key>keyEquivalent</key>
	<string>^~C</string>
	<key>name</key>
	<string>Cabal</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>^(\s*)(exposed-modules):$</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.other.cabal</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?!\1\s)</string>
			<key>name</key>
			<string>exposed.modules.cabal</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#module_name</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(\s*)(build-depends):$</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.other.cabal</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?!\1\s)</string>
			<key>name</key>
			<string>exposed.modules.cabal</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>([&lt;&gt;=]+)|([&amp;|]+)</string>
					<key>name</key>
					<string>keyword.operator.haskell</string>
				</dict>
				<dict>
					<key>match</key>
					<string>((\d+|\*)\.)*(\d+|\*)</string>
					<key>name</key>
					<string>constant.numeric.haskell</string>
				</dict>
				<dict>
					<key>match</key>
					<string>([\w\-]+)</string>
					<key>name</key>
					<string>support.function.haskell</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.other.cabal</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.entity.cabal</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*([a-zA-Z_-]+)(:)\s+</string>
			<key>name</key>
			<string>entity.cabal</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.entity.cabal</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.cabal</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(?i)(executable|library|test-suite|benchmark|flag|source-repository)\s+([^\s,]+)\s*$</string>
			<key>name</key>
			<string>entity.cabal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)library\s*$</string>
			<key>name</key>
			<string>keyword.entity.cabal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>--.*$</string>
			<key>name</key>
			<string>comment.cabal</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>module_name</key>
		<dict>
			<key>match</key>
			<string>([A-Z][A-Za-z_'0-9]*)(\.[A-Z][A-Za-z_'0-9]*)*</string>
			<key>name</key>
			<string>storage.module.haskell</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.cabal</string>
	<key>uuid</key>
	<string>22F622A3-4F1D-4D66-999F-10D42FBFFC4D</string>
</dict>
</plist>
