<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>keyEquivalent</key>
	<string>^~G</string>
	<key>name</key>
	<string>Haskell Output Panel</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>^(Errors): (\d+), (Warnings): (\d+), (Hints): (\d+)$</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.level.outputpanel</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.level.outputpanel</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>keyword.level.outputpanel</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.outputpanel</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.outputpanel</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.outputpanel</string>
				</dict>
			</dict>
			<key>name</key>
			<string>location.outputpanel</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(Errors|Warnings|Hints): (\d+)$</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.level.outputpanel</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.outputpanel</string>
				</dict>
			</dict>
			<key>name</key>
			<string>messages.outputpanel</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#report</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#message</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#location</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#quote</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>report</key>
		<dict>
			<key>match</key>
			<string>^\s{2}((?:\w:)?[^:]+):\sline\s(\d+),\scolumn\s(\d+):</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.location.outputpanel</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.outputpanel</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.outputpanel</string>
				</dict>
			</dict>
			<key>name</key>
			<string>location.outputpanel</string>
		</dict>
		<key>message</key>
		<dict>
			<key>match</key>
			<string>^\s{4}(Hint|Warning|Error):</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.level.outputpanel</string>
				</dict>
			</dict>
			<key>name</key>
			<string>message.outputpanel</string>
		</dict>
		<key>location</key>
		<dict>
			<key>match</key>
			<string>at\s([^:]+):(\d+):(\d+)\-(\d+)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.location.outputpanel</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.outputpanel</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.outputpanel</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.outputpanel</string>
				</dict>
			</dict>
			<key>name</key>
			<string>location.outputpanel</string>
		</dict>
		<key>quote</key>
		<dict>
			<key>match</key>
			<string>`([^']+)'</string>
			<key>name</key>
			<string>constant.character.outputpanel</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source</string>
	<key>uuid</key>
	<string>D76B7000-2B09-11E4-8C21-0800200C9A66</string>
</dict>
</plist>
