<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>keyEquivalent</key>
	<string>^~G</string>
	<key>name</key>
	<string>Haskell Symbol Info Panel</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>^(class|type|data|newtype)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.type.symbolinfo keyword.declaration.data.haskell</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?!\s)</string>
			<key>name</key>
			<string>symbol.type.symbolinfo</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#type</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>#constructor_signature</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#function_signature</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^Imported from (.*)$</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.module.symbolinfo</string>
				</dict>
			</dict>
			<key>name</key>
			<string>comment.import.symbolinfo</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(Project|Defined (at|in)|Package|Installed in|Hackage URL): (.*)$</string>
			<key>captures</key>
			<dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.quoted.double.symbolinfo</string>
				</dict>
			</dict>
			<key>name</key>
			<string>comment.details.symbolinfo</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>type</key>
		<dict>
			<key>patterns</key>
			<array>
 				<dict>
					<key>match</key>
					<string>-&gt;|→</string>
					<key>name</key>
					<string>keyword.operator.arrow.haskell</string>
				</dict>
				<dict>
					<key>match</key>
					<string>=&gt;|⇒</string>
					<key>name</key>
					<string>keyword.operator.big-arrow.haskell</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(Int(eger)?|Maybe|Either|Bool|Float|Double|Char|String|Ordering|ShowS|ReadS|FilePath|IO(Error)?)\b</string>
					<key>name</key>
					<string>storage.type.haskell support.type.haskell</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;!')\b[a-z][A-Za-z_'0-9]*\b</string>
					<key>name</key>
					<string>variable.generic.haskell</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;!')\b[A-Z][A-Za-z_'0-9]*\b</string>
					<key>name</key>
					<string>storage.type.haskell</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\(\)</string>
					<key>name</key>
					<string>storage.type.haskell</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\()</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.haskell</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\))</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.haskell</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.type_signature.brace.haskell</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#type</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\[)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.haskell</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\])</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.haskell</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.type_signature.list.haskell</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#type</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>function_signature</key>
		<dict>
			<key>begin</key>
			<!--
			SublimeText2 workaround
			If begin doesn't capture anything (using only lookaheads), then end tries match just from the beginning
			And it cause infinite loop in case of function with no indentation (so there's nothing matched)
			SublimeText3 works well in that case

			We also can't match full name of function, because there're cases with several names:
				* x, y, z :: Int
				* [x, y, z] :: [Int]

			Therefore we are just trying to much something: name, open bracket etc.
			And we match other stuff within patterns
			-->
			<!-- <string>^(\s*)(?!--)(?=([\w\s,']*|\(.*\)|\[.*\])\s+((::)|∷))</string> -->
			<string>^(\s*)(?!--)(?:(\(\W\)|[\w']+)|[\(\[])(?=[\w',\s\[\]\(\)]*((?:::)|∷))</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.haskell</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?!\1\s)|(?=})</string>
			<key>name</key>
			<string>meta.declaration.function.haskell</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?=.*((::)|∷))</string>
					<key>end</key>
					<string>((::)|∷)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.double-colon.haskell</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.declaration.function.names.haskell</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>((?&lt;!')\b[a-z_][\w']*|\(\W+\))</string>
							<key>name</key>
							<string>entity.name.function.haskell</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#type</string>
				</dict>
			</array>
		</dict>
		<key>constructor_signature</key>
		<dict>
			<key>begin</key>
			<string>^(\s+)([A-Z][\w']*|\(\W+\))\s*((::)|∷)</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.haskell entity.name.constructor.haskell</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.other.double-colon.haskell</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?!\1\s)</string>
			<key>name</key>
			<string>meta.declaration.function.haskell</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#type</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source</string>
	<key>uuid</key>
	<string>6ED96FDF-2496-4770-9175-C3CFCFF1D9E5</string>
</dict>
</plist>
